document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head lang=\'en\'>");
document.writeln("<meta charset=\'UTF-8\'>");
document.writeln("");
document.writeln("<link type=\'text/css\' rel=\'stylesheet\' href=\'css/footer1.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("");
document.writeln("            ");
document.writeln("                <div class=\'footer\'>  ");
document.writeln("                        ");
document.writeln("                                ");
document.writeln("                                     <a href=\'#\' target=\'_blank\'>关于我们</a> ");
document.writeln("                                     <span class=\'pipe\'>|</span> ");
document.writeln("                                     <a href=\'#\' target=\'_blank\'>联系我们</a> ");
document.writeln("                                     <span class=\'pipe\'>|</span> ");
document.writeln("                                     <a href=\'#\' target=\'_blank\'>法律声明</a> <br>");
document.writeln("                                    <p>Copyright &copy;2018 XIDIAN UNIVERSITY Supreme 602 All Rights Reserved. ");
document.writeln("                                    </p>");
document.writeln("                </div>");
document.writeln("                       ");
document.writeln("");
document.writeln("              ");
document.writeln("            ");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");