document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head lang=\'en\'>");
document.writeln("<meta charset=\'UTF-8\'>");
document.writeln("<title>舆情</title>");
document.writeln("");
document.writeln("<link type=\'text/css\' rel=\'stylesheet\' href=\'css/header.css\'>");
document.writeln("");
document.writeln("<script src=\'js/jquery-1.9.1.min.js\'></script>");
document.writeln("<script src=\'js/login.js\'></script>");
document.writeln("<link rel=\'stylesheet\' href=\'http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css\'>");
document.writeln("	<script src=\'http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js\'></script>");
document.writeln("	<script src=\'http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js\'></script>");
document.writeln("");
document.writeln("</head>");
document.writeln("<body >");
document.writeln("    ");
document.writeln("<nav class=\'header\' align=\'center\' >");
document.writeln("		");
document.writeln("			<div class=\'dropdown\' >");
document.writeln("					<button type=\'button\' class=\'btn dropdown-toggle\' id=\'dropdownMenu1\' data-toggle=\'dropdown\'>");
document.writeln("						热点事件");
document.writeln("						<span class=\'caret\'></span>");
document.writeln("					</button>");
document.writeln("					<ul class=\'dropdown-menu\' role=\'menu\' aria-labelledby=\'dropdownMenu1 \'>");
document.writeln("						<li role=\'presentation\'>");
document.writeln("							<a role=\'menuitem\' tabindex=\'-1\' href=\'ReDianZhiShu.html\'>热点指数</a>");
document.writeln("						</li>");
document.writeln("						<li role=\'presentation\' class=\'divider\'></li>");
document.writeln("						<li role=\'presentation\'>");
document.writeln("							<a role=\'menuitem\' tabindex=\'-1\' href=\'hot.html\'>热点传播分析</a>");
document.writeln("						</li>");
document.writeln("						<li role=\'presentation\' class=\'divider\'></li>");
document.writeln("						<li role=\'presentation\'>");
document.writeln("							<a role=\'menuitem\' tabindex=\'-1\' href=\'header.html\'>热点态势分析</a>");
document.writeln("						</li>");
document.writeln("						<li role=\'presentation\' class=\'divider\'></li>");
document.writeln("						<li role=\'presentation\'>");
document.writeln("							<a role=\'menuitem\' tabindex=\'-1\' href=\'footer.html\'>热点舆情引导</a>");
document.writeln("						</li>");
document.writeln("					</ul>");
document.writeln("			</div>");
document.writeln("			<div class=\'dropdown\' >");
document.writeln("					<button type=\'button\' class=\'btn dropdown-toggle\' id=\'dropdownMenu1\' data-toggle=\'dropdown\'>");
document.writeln("							信息监测");
document.writeln("							<span class=\'caret\'></span>");
document.writeln("						</button>");
document.writeln("						<ul class=\'dropdown-menu\' role=\'menu\' aria-labelledby=\'dropdownMenu1 \'>");
document.writeln("							<li role=\'presentation\'>");
document.writeln("								<a role=\'menuitem\' tabindex=\'-1\' href=\'YongHuJianCe.html\'>用户监测</a>");
document.writeln("							</li>");
document.writeln("							<li role=\'presentation\' class=\'divider\'></li>");
document.writeln("							<li role=\'presentation\'>");
document.writeln("								<a role=\'menuitem\' tabindex=\'-1\' href=\'YongHuXinXiJianCe.html\'>用户信息监测</a>");
document.writeln("							</li>");
document.writeln("							<li role=\'presentation\' class=\'divider\'></li>");
document.writeln("							<li role=\'presentation\'>");
document.writeln("								<a role=\'menuitem\' tabindex=\'-1\' href=\'YongHuYinDaoCuoShi.html\'>用户引导措施</a>");
document.writeln("							</li>");
document.writeln("							");
document.writeln("						</ul>");
document.writeln("					");
document.writeln("			</div>		");
document.writeln("			<div class=\'dropdown\' >");
document.writeln("					<button type=\'button\' class=\'btn dropdown-toggle\' id=\'dropdownMenu1\' data-toggle=\'dropdown\'>");
document.writeln("							舆情演化");
document.writeln("							<span class=\'caret\'></span>");
document.writeln("						</button>");
document.writeln("					");
document.writeln("			</div>");
document.writeln("			<div class=\'dropdown\' >");
document.writeln("					<button type=\'button\' class=\'btn dropdown-toggle\' id=\'dropdownMenu1\' data-toggle=\'dropdown\'>");
document.writeln("							事件分析");
document.writeln("							<span class=\'caret\'></span>");
document.writeln("						</button>");
document.writeln("					");
document.writeln("			</div>");
document.writeln("		");
document.writeln("		");
document.writeln("");
document.writeln("			<div >	");
document.writeln("			<button id=\'login\'> 登陆</button>");
document.writeln("            </div>");
document.writeln("            <div class=\'overCurtain\' ></div>");
document.writeln("");
document.writeln("			<div class=\'hide-center\'>");
document.writeln("				<div id=\'formhead\'>");
document.writeln("					<button type=\'button\' id=\'close\'>X</button>");
document.writeln("				</div>");
document.writeln("				<div id=\'formbody\'>");
document.writeln("					<div class=\'loginUserName\'>");
document.writeln("						<input id=\'input-topright-loginInput\' name=\'userName\' class=\'loginInput1\' placeholder=\'用户名\' type=\'text\' value=\'\'>");
document.writeln("					</div>");
document.writeln("					<div class=\'loginPassword\'>");
document.writeln("						<input id=\'input-bottomright-loginInput\' name=\'password\' class=\'loginInput2\' placeholder=\'密码\' type=\'password\' value=\'\' >");
document.writeln("						<!-- style=\'border-bottom-right-radius:5px;\' -->");
document.writeln("					</div>");
document.writeln("					<div id=\'formfoot\'>");
document.writeln("						<a href=\'Zuodaohang1.html\'><button id=\'BSignIn\' type=\'submit\'>登陆</button></a>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("            </div>");
document.writeln("        ");
document.writeln("");
document.writeln("</nav>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");