document.writeln("<!DOCTYPE html>  ");
document.writeln("<html>  ");
document.writeln("<head>  ");
document.writeln("    <meta charset=\'UTF-8\' />  ");
document.writeln("    <title>进度条 学习</title>  ");
document.writeln("    <script src=\'https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js\'></script>  ");
document.writeln("    <style>  ");
document.writeln("        .progress{position: relative; width:300px;margin:100px auto;}  ");
document.writeln("        .progress_bg{height: 10px; border: 1px solid #ddd; overflow: hidden;background-color:#f2f2f2;}  ");
document.writeln("        .progress_bar{background: #0088cc; width: 0; height: 10px; border-radius: 5px;}  ");
document.writeln("        .progress_btn{width: 10px; height: 20px; position: absolute;background:#0088cc;   ");
document.writeln("        left: 0px; margin-left: -10px; top:-5px; cursor: pointer;border:1px #0088cc;box-sizing:border-box;}  ");
document.writeln("        .progress_btn:hover{border-color:#0088cc;border-radius: 6px;}  ");
document.writeln("    </style>  ");
document.writeln("</head>  ");
document.writeln("<body>  ");
document.writeln("    <div class=\'progress\'>  ");
document.writeln("        <div class=\'progress_bg\'>  ");
document.writeln("            <div class=\'progress_bar\'></div>  ");
document.writeln("        </div>  ");
document.writeln("        <div class=\'progress_btn\'></div>  ");
document.writeln("        <div class=\'text\'>0%</div>  ");
document.writeln("    </div>  ");
document.writeln("<script type=\'text/javascript\'>  ");
document.writeln("$(function(){  ");
document.writeln("    var tag = false,ox = 0,left = 0,bgleft = 0;  ");
document.writeln("    $(\'.progress_btn\').mousedown(function(e) {  ");
document.writeln("        ox = e.pageX - left;  ");
document.writeln("        tag = true;  ");
document.writeln("    });  ");
document.writeln("  ");
document.writeln("    $(document).mouseup(function() {  ");
document.writeln("        tag = false;  ");
document.writeln("    });  ");
document.writeln("  ");
document.writeln("    $(\'.progress\').mousemove(function(e) {//鼠标移动  ");
document.writeln("        if (tag) {  ");
document.writeln("             left = e.pageX - ox;  ");
document.writeln("             if (left <= 0) {  ");
document.writeln("                left = 0;  ");
document.writeln("             }else if (left > 300) {  ");
document.writeln("                left = 300;  ");
document.writeln("             }  ");
document.writeln("            $(\'.progress_btn\').css(\'left\', left);  ");
document.writeln("            $(\'.progress_bar\').width(left);  ");
document.writeln("            $(\'.text\').html(parseInt((left/300)*100) + \'%\');  ");
document.writeln("        }  ");
document.writeln("    });  ");
document.writeln("  ");
document.writeln("    // $(\'.progress_bg\').click(function(e) {//鼠标点击  ");
document.writeln("    //      if (!tag) {  ");
document.writeln("    //          bgleft = $(\'.progress_bg\').offset().left;  ");
document.writeln("    //          left = e.pageX - bgleft;  ");
document.writeln("    //          if (left <= 0) {  ");
document.writeln("    //              left = 0;  ");
document.writeln("    //         }else if (left > 300) {  ");
document.writeln("    //              left = 300;  ");
document.writeln("    //         }  ");
document.writeln("    //         $(\'.progress_btn\').css(\'left\', left);  ");
document.writeln("    //         $(\'.progress_bar\').animate({width:left},300);  ");
document.writeln("    //         $(\'.text\').html(parseInt((left/300)*100) + \'%\');  ");
document.writeln("    //      }  ");
document.writeln("    // });  ");
document.writeln("});  ");
document.writeln("</script>  ");
document.writeln("</body>  ");
document.writeln("</html>");